language: rust
sudo: false
rust: nightly

matrix:
  fast_finish: true
  include:
    # Linux:
    - env: TARGET=i586-unknown-linux-gnu
      name: "i586-unknown-linux-gnu"
    - env: TARGET=i686-unknown-linux-gnu
      name: "i686-unknown-linux-gnu"
    - env: TARGET=x86_64-unknown-linux-gnu
      name: "x86_64-unknown-linux-gnu"
      install: true
    # MacOSX:
    - os: osx
      env: TARGET=i686-apple-darwin
      name: "i686-apple-darwin"
      script: ci/run.sh
      osx_image: xcode9.4
    - os: osx
      env: TARGET=x86_64-apple-darwin
      name: "x86_64-apple-darwin"
      install: true
      script: ci/run.sh
      osx_image: xcode9.4
    # TOOLS:
    - name: "Documentation"
      script: ci/dox.sh
    - name: "rustfmt"
      install: true
      before_script: rustup component add rustfmt-preview
      script: cargo fmt --all -- --check
    - name: "clippy"
      install: true
      before_script: rustup component add clippy-preview
      script: cargo clippy --all -- -D clippy::pedantic

install: travis_retry rustup target add $TARGET
before_script: cargo generate-lockfile
script: travis_wait 50 ci/run-docker.sh

env:
  global:
    secure: ""
notifications:
  email:
    on_success: never
